app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#EndroidTwitterBundle:
#    resource:   "@EndroidTwitterBundle/Controller/"
#    type:       annotation
#    prefix:     /twitterapi

WallPosterBundle:
    resource: "@WallPosterBundle/Resources/routing/routing.yml"